swagger: "2.0"
info:
  description: "Bank Argent API documentation (transaction page): contains all available API endpoints  in this codebase."
  version: "1.0.0"
  title: "Bank Argent API documentation"
  termsOfService: "http://swagger.io/terms/"
 
host: "localhost:3001"
basePath: "/api/v1"
schemes:
- "https"
- "http"
paths:
  /user/profile:
    post:
      security:
      - Bearer: []
      tags:
      - "User Module"
      summary: "User Profile API"
      description: "API for fetching user profile"
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Attach Bearer JWT token"
        required: true
        type: "string"
      responses:
        "200":
          description: "User profile retrieved successully"
          schema:
            $ref: "#/definitions/User"
        "400":
          description: "Invalid Fields"
        "500":
          description: "Internal Server Error"
    put:
      security:
      - Bearer: []
      tags:
      - "User Module"
      summary: "User Profile API"
      description: "API for updating a user profile"
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Attach Bearer JWT token"
        required: true
        type: "string"
      - name: "body"
        in: "body"
        description: "Update user profile attributes"
        schema:
            $ref: "#/definitions/UserProfile"
        required: true
      responses:
        "200":
          description: "User profile retrieved successully"
          schema:
            $ref: "#/definitions/UserProfile"
        "400":
          description: "Invalid Fields"
        "500":
          description: "Internal Server Error"
          
  
  /user/profile/{accountId}:
    get:
      security:
         - Bearer: []
      tags:
         - "User Transactions"
      summary: "User's account transactions" 
      description: "Get user's account transactions"
      produces:
        - "application/json"
      parameters:
        - name: "Authorization"
          in: "header"
          description: "Attach Bearer JWT token"
          required: true
          type: "string"
        - name: "accountId"
          in: "path"
          description: "User's Account ID"
          required: true
          type: integer
       
      responses:
          '200':
            description: "User transactions retrieved Successfully"
            schema:
              $ref: '#/definitions/UserAccount'
          '400':
            description: "Invalid Fields"
          '500':
            description: "Internal Server Error"
          
  /user/profile/{accountId}/{transactionID}:
    get:
      security: 
        - Bearer: []
      tags:
        - "User account transaction details"
      summary: "User account transaction details"
      description: "Get account transaction details"
      produces:
        - "application/json"
      parameters:
        - name: "Authorization"
          in: "header"
          description: "Attach Bearer JWT token"
          required: true
          type: "string"
        - name: "accountId"
          in: "path"
          description: "User's Account ID"
          required: true
          type: integer
        - name: "transactionID"
          in: "path"
          description: "Transaction's ID"
          required: true
          type: integer
            
      responses:
          '200':
            description: "User account transactions details retrieved Successfully"
            schema: 
              $ref: '#/definitions/UserAccount'
          '400':
            description: "Invalid Fields"
          '500':
            description: "Internal Server Error"
        
    put:
      security:
        - Bearer: []
      tags:
          - "User account transaction details" 
      summary: "User account transaction details"
      description: "Modify user account transaction details"
      produces:
          - "application/json"
      parameters:
          - name: "Authorization"
            in: "header"
            description: "Attach Bearer JWT token"
            required: true
            type: "string"
          - name: "body"
            in: "body"
            description: "Update transaction details"
            schema:
              $ref: "#/definitions/UserTransactionDetails"
            required: true
          - name: "accountId"
            in: "path"
            description: "User's Account ID"
            required: true
            type: integer
          - name: "transactionID"
            in: "path"
            description: "Transaction's ID"
            required: true
            type: integer
      responses:
          '200': 
            description: "User account transaction details retrieved successfully"
            schema: 
              $ref: '#/definitions/UserAccount'
        
          '400':
            description: "Invalid Fields"
          '500': 
            description: "Internal Server Error"
            
  
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    
definitions:
  User:
    properties:
      status:
        type: "integer"
      email:
        type: "string"
      id:
        type: "string"
  
  UserProfile:
    properties:
      firstname:
        type: "string"
      Lastname:
        type: "string"
  
  UserAccount:
    properties:
      date:
        type: "string"
        description: "transaction date"
      description:
        type: "string"
        description: "transaction description"
      amount:
        type: "integer"
        description: "transaction amount"  
      balance:
        type: "integer"
        description: "account balance"
      type:
        type: "string"
        description: "transaction type"
      category:
        type: "string"
        description: "transaction category"
      notes:
        type: "string"
        description: "transaction notes"
  
  UserTransactionDetails:
    type: object
    properties:
      Category:
        type: "string"
        description: "Transaction category"
      Notes:
        type: "string"
        description: "Transaction Notes"
      


        
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"